[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirecionamentos para páginas de sucesso do formulário
[[redirects]]
  from = "/contato/sucesso"
  to = "/sucesso.html"
  status = 301

[[redirects]]
  from = "/contato/sucesso/"
  to = "/sucesso.html"
  status = 301

[[redirects]]
  from = "/sucesso/"
  to = "/sucesso.html"
  status = 301

# Redirecionamento para 404 (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

# Headers para otimização de cache
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para MIME types corretos
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"

# Headers específicos para formulários de contato
[[headers]]
  for = "/contato/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuração padrão para formulários
[context.production]
  [context.production.environment]
    NETLIFY_FORMS_REDIRECT = "/obrigado.html"